import { formatCurrency } from '../constants/currency';
import { APP_NAME } from '../constants/brand';
import type { BudgetStat, DailyTrendPoint, SpendingSlice } from './index';

export type ReportPeriod = 'daily' | 'weekly' | 'monthly' | 'yearly';

export type ReportPeriodRange = {
  period: ReportPeriod;
  start: string;
  end: string;
  label: string;
};

function pad2(value: number): string {
  return String(value).padStart(2, '0');
}

function toIsoDay(date: Date): string {
  return `${date.getFullYear()}-${pad2(date.getMonth() + 1)}-${pad2(date.getDate())}`;
}

function startOfWeekMonday(date: Date): Date {
  const result = new Date(date.getFullYear(), date.getMonth(), date.getDate());
  const day = result.getDay(); // 0 Sun .. 6 Sat
  const diff = day === 0 ? -6 : 1 - day;
  result.setDate(result.getDate() + diff);
  return result;
}

export function getReportPeriodRange(
  period: ReportPeriod,
  anchor: Date = new Date()
): ReportPeriodRange {
  const base = new Date(anchor.getFullYear(), anchor.getMonth(), anchor.getDate());

  if (period === 'daily') {
    const iso = toIsoDay(base);
    return {
      period,
      start: iso,
      end: iso,
      label: base.toLocaleDateString('en-PH', {
        weekday: 'long',
        month: 'long',
        day: 'numeric',
        year: 'numeric',
      }),
    };
  }

  if (period === 'weekly') {
    const start = startOfWeekMonday(base);
    const end = new Date(start);
    end.setDate(start.getDate() + 6);
    return {
      period,
      start: toIsoDay(start),
      end: toIsoDay(end),
      label: `Week of ${start.toLocaleDateString('en-PH', { month: 'short', day: 'numeric' })} – ${end.toLocaleDateString('en-PH', { month: 'short', day: 'numeric', year: 'numeric' })}`,
    };
  }

  if (period === 'yearly') {
    const start = new Date(base.getFullYear(), 0, 1);
    const end = new Date(base.getFullYear(), 11, 31);
    return {
      period,
      start: toIsoDay(start),
      end: toIsoDay(end),
      label: String(base.getFullYear()),
    };
  }

  const start = new Date(base.getFullYear(), base.getMonth(), 1);
  const end = new Date(base.getFullYear(), base.getMonth() + 1, 0);
  return {
    period: 'monthly',
    start: toIsoDay(start),
    end: toIsoDay(end),
    label: base.toLocaleString('en-PH', { month: 'long', year: 'numeric' }),
  };
}

export const REPORT_PERIOD_OPTIONS: Array<{ value: ReportPeriod; label: string }> = [
  { value: 'daily', label: 'Daily' },
  { value: 'weekly', label: 'Weekly' },
  { value: 'monthly', label: 'Monthly' },
  { value: 'yearly', label: 'Yearly' },
];

export type FinanceReportInput = {
  periodLabel: string;
  balance: number;
  income: number;
  expenses: number;
  budgetSpend: number;
  spending: SpendingSlice[];
  budgets: BudgetStat[];
};

export function formatFinanceReportText(input: FinanceReportInput): string {
  const net = input.income - input.expenses;
  const lines: string[] = [
    `${APP_NAME} — Finance report`,
    `Period: ${input.periodLabel}`,
    '',
    `Current Balance: ${formatCurrency(input.balance)}`,
    `Income: ${formatCurrency(input.income)}`,
    `Expenses: ${formatCurrency(input.expenses)}`,
    `Net: ${formatCurrency(net, { showSign: true })}`,
    `Budget plan spend: ${formatCurrency(input.budgetSpend)}`,
    '',
  ];

  if (input.budgets.length > 0) {
    lines.push('Budgets');
    for (const budget of input.budgets) {
      const left = Math.max(0, budget.total - budget.spent);
      lines.push(
        `• ${budget.name}: spent ${formatCurrency(budget.spent)} of ${formatCurrency(budget.total)} (${budget.percent}%) · left ${formatCurrency(left)}`
      );
    }
    lines.push('');
  }

  if (input.spending.length > 0) {
    lines.push('Spending by category');
    for (const slice of input.spending) {
      lines.push(`• ${slice.name}: ${formatCurrency(slice.total)} (${slice.percent}%)`);
    }
    lines.push('');
  }

  lines.push(`Generated by ${APP_NAME}`);
  return lines.join('\n');
}

export function buildFinanceReportMailto(input: {
  toEmail: string;
  report: FinanceReportInput;
}): string {
  const subject = `${APP_NAME} ${input.report.periodLabel} report`;
  const body = formatFinanceReportText(input.report);
  return `mailto:${input.toEmail}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
}

/** True when last send was before the current report period started. */
export function isReportEmailDue(
  lastSentAt: string | null | undefined,
  period: ReportPeriod,
  anchor: Date = new Date()
): boolean {
  if (!lastSentAt) return true;
  const last = new Date(lastSentAt);
  if (Number.isNaN(last.getTime())) return true;
  const range = getReportPeriodRange(period, anchor);
  const lastIso = toIsoDay(last);
  return lastIso < range.start;
}

function shortLabel(iso: string): string {
  const [year, month, day] = iso.split('-').map(Number);
  const date = new Date(year, (month || 1) - 1, day || 1);
  return date.toLocaleDateString('en-PH', { month: 'short', day: 'numeric' });
}

export function buildPeriodTrend(
  rows: Array<{ transaction_date: string; type: string; amount: number }>,
  range: ReportPeriodRange
): DailyTrendPoint[] {
  if (range.period === 'yearly') {
    const buckets = new Map<string, { income: number; expense: number; label: string }>();
    for (let month = 0; month < 12; month += 1) {
      const key = `${range.start.slice(0, 4)}-${pad2(month + 1)}`;
      const label = new Date(Number(range.start.slice(0, 4)), month, 1).toLocaleDateString('en-PH', {
        month: 'short',
      });
      buckets.set(key, { income: 0, expense: 0, label });
    }
    for (const row of rows) {
      const key = row.transaction_date.slice(0, 7);
      const bucket = buckets.get(key);
      if (!bucket) continue;
      if (row.type === 'income') bucket.income += Number(row.amount ?? 0);
      if (row.type === 'expense') bucket.expense += Number(row.amount ?? 0);
    }
    return [...buckets.entries()].map(([date, totals]) => ({
      date: `${date}-01`,
      label: totals.label,
      income: Math.round(totals.income * 100) / 100,
      expense: Math.round(totals.expense * 100) / 100,
    }));
  }

  const start = new Date(
    Number(range.start.slice(0, 4)),
    Number(range.start.slice(5, 7)) - 1,
    Number(range.start.slice(8, 10))
  );
  const end = new Date(
    Number(range.end.slice(0, 4)),
    Number(range.end.slice(5, 7)) - 1,
    Number(range.end.slice(8, 10))
  );
  const buckets = new Map<string, { income: number; expense: number }>();
  for (let cursor = new Date(start); cursor <= end; cursor.setDate(cursor.getDate() + 1)) {
    buckets.set(toIsoDay(cursor), { income: 0, expense: 0 });
  }
  for (const row of rows) {
    const bucket = buckets.get(row.transaction_date);
    if (!bucket) continue;
    if (row.type === 'income') bucket.income += Number(row.amount ?? 0);
    if (row.type === 'expense') bucket.expense += Number(row.amount ?? 0);
  }
  return [...buckets.entries()].map(([date, totals]) => ({
    date,
    label: shortLabel(date),
    income: Math.round(totals.income * 100) / 100,
    expense: Math.round(totals.expense * 100) / 100,
  }));
}
