packages:
  - "apps/*"
  - "packages/*"
nodeLinker: isolated
virtualStoreDir: D:/p
virtualStoreDirMaxLength: 20
peersSuffixMaxLength: 8
allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - '@expo/cli@57.0.16'
  - '@expo/fingerprint@0.20.8'
  - expo-asset@57.0.12
overrides:
  react: 19.2.3
  react-dom: 19.2.3
